// Angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/router';
import '@angular/forms';
import 'jquery';
import 'bootstrap/dist/js/bootstrap';